extends Node
var transition_variable: int = 0
var transition_variable_2: int = 2
var words = [
	"great",
	"animal",
	"keep",
	"name",
	"away",
	"together",
	"been",
	"should",
	"four",
	"every",
	"number",
	"hand",
	"again",
	"before",
	"over",
	"make",
	"grow",
	"soon",
	"begin",
	"animal",
	"your",
	"thing",
	"mean",
	"write",
	"while",
	"letter",
	"before",
	"name",
	"night",
	"must",
	"mean",
	"home",
	"which",
	"time",
	"left",
	"make",
	"year",
	"around",
	"story",
	"sometimes",
	"group",
	"took",
	"begin",
	"mother",
	"river",
	"earth",
	"some",
	"point",
	"give",
	"went",
	"give",
	"through",
	"without",
	"study",
	"miss",
	"this",
	"really",
	"family",
	"carry",
	"know",
	"took",
	"read",
	"began",
	"year",
	"feet",
	"father",
	"animation", 
	"reincarnate",
	"apartment", 
	"technology",
	"cognitive",
	"disciplined",
	"stretched",
	"foresight",
	"prospicient",
	"ferocious",
	"translucent",
	"elongate",
	"alchemized",
	"appreciate",
	"knockback",
	"fortnight",
	"skydivers",
	"snazziness",
	"background",
	"blackberry",
	"additional",
	"journalist",
	"justifying",
	"backbiting",
	"babysitter",
	"kidnapping",
	"kindliness",
	"confidence",
	"commitment",
	"collective",
	"contribute",
	"literature",
	"leadership",
	"discipline",
	"discussion",
	"difficulty",
	"distribute",
	"membership",
	"moderation",
	"efficiency",
	"experience",
	"everything",
	"especially",
	"narcissist",
	"navigation",
	"frequently",
	"friendship",
	"faithfully",
	"forcefully",
	"occupation",
	"oppression",
	"generation",
	"gracefully",
	"government",
	"grapefruit",
	"previously",
	"perception",
	"healthcare",
	"hesitation",
	"hydrometer",
	"highlander",
	"quarantine",
	"qualifying",
	"impossible",
	"investment",
	"initiative"
]




var words3 = [
	"incomprehensibility",
	"dichlorodifluoromethane",
	"compartmentalised",
	"nonreciprocating",
	"conventionalise",
	"compartmentalise",
	"internationalise",
	"professionalise",
	"conceptualisation",
	"chlorofluorocarbon",
	"paraprofessional",
	"decriminalisation",
	"collectivisation",
	"professionalisation",
	"parapsychologist",
	"compartmentalize",
	"weatherstripping",
	"electroencephalographic",
	"individualistically",
	"reprehensibility",
	"dichlorodiphenyltrichloroethane",
	"intercommunicate",
	"contraindication",
	"deconstruction",
	"photoelectrically",
	"socioeconomically",
	"sentimentalization",
	"nonrepresentational",
	"methodologically",
	"particularisation",
	"denationalisation",
	"electroencephalogram",
	"electrocardiography",
	"antiauthoritarian",
	"tenderheartedness",
	"hyperventilation",
	"microelectronic",
	"oversensitiveness",
	"wholeheartedness",
	"compartmentalization",
	"discombobulate",
	"conceptualization",
	"electrocardiograph",
	"interelationship",
	"valetudinarianism",
	"internationalisation",
	"particularization",
	"overcompensation",
	"countersignature",
	"inconspicuousness",
	"hydroelectricity",
	"misappropriate",
	"interchangeability",
	"multifariousness",
	"commercialisation",
	"decriminalization",
	"oversimplification",
	"mispronunciation",
	"discontinuation",
	"pseudoscientific",
	"phantasmagorical",
	"contemptuousness",
	"transmogrification",
	"denationalization",
	"underdevelopment",
	"undernourishment"
]



var special_characters = [
	".",
	"!",
	"?",
]



func get_prompt() -> String:

		var word_index = randi() % words.size()
		var special_index = randi() % special_characters.size()

		var word = words[word_index]

		var actual_word = word
		
		return actual_word 
		



func get_prompt2() -> String:
		
		var word_index = randi() % words3.size()
		var special_index = randi() % special_characters.size()

		var word = words3[word_index]
		var special_character = special_characters[special_index]

		var actual_word2 = word.substr(0, 1).to_upper() + word.substr(1).to_lower() 
	
		return actual_word2 + special_character
